sudo: required
services:
  - docker

before_install:
  - docker build -t youssefmostafa2510/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true youssefmostafa2510/docker-react npm run test
